manifold/specs: create logspout daemonset forwarding logs to papertrail
gliderlabs/infra.gl pull request #8
Opened 2017-03-31 22:09 UTC by mattaitchison

2017-03-31 22:11 UTC, mattaitchison commented on manifold/specs/logspout.yaml
> +        args: ["syslog+tls://logs5.papertrailapp.com:31048"]
Probably shouldn't hardcode the endpoint here.

2017-04-03 22:10 UTC, progrium commented on manifold/specs/logspout.yaml
> +        args: ["syslog+tls://logs5.papertrailapp.com:31048"]
It's just this one place, pretty clear from filename where it might be. I say leave it.

2017-04-03 22:11 UTC, progrium commented
These aren't automatically applied. Needs to also be added here https://github.com/gliderlabs/infra.gl/blob/master/manifold/cluster.tf#L53

2017-04-03 22:13 UTC, progrium approved these changes

2017-04-03 22:13 UTC, progrium requested changes
Add to cluster.tf

2017-04-03 22:19 UTC, progrium approved these changes

2017-04-03 23:08 UTC, merged